name: 'Check Task definition'
description: 'Checks task_definition.json with application.yaml and task_definition.json with <env>.tfstate (S3 based)'

inputs:
  task-definition:
    description: 'Task Definition json file path'
    required: true
  app-config:
    description: 'Application properties yaml file'
    required: true
  gha-path:
    description: 'github action checkout path'
    default: "."

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip  dependencies
        cache-dependency-path: ${{ inputs.gha-path}}/aws/check-task-definition/requirements.txt'
    - name: Install Python dependencies
      shell: bash
      run: pip install -r scripts/aws/check-task-definition/requirements.txt
    - name: Execute Validation
      shell: bash
      run: |
        python scripts/aws/check-task-definition \
          --task-definition ${{ inputs.task-definition }} \
          --app-config ${{ inputs.app-config }}