# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - aws/check-task-definition/**
      - actions/check-task-definition
      - .github/workflows/python-app.yml

permissions:
  contents: read

jobs:
  check-task-definition-unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip  dependencies
          cache-dependency-path: 'aws/check-task-definition/requirements.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f aws/check-task-definition/requirements.txt ]; then pip install -r aws/check-task-definition/requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run Check Task Definition Unit Tests
        run: pytest aws/check-task-definition/unittests.py
  check-task-definition-integrationtest:
    needs:
      - check-task-definition-unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Integration test 1
        uses: ./actions/check-task-definition
        with:
          task-definition: "some/dummy/path/task_definition.json"
          app-config: "some/dummy/path/application.yaml"
